### ISSUE TITLE
Nummer für Honorarnote eingeben

### ISSUE THREAD

**Issue by gws4259** [irisSchaffer/OEBS_Honorarnoten#28]
Manche Betreuer (vermutlich die UST-pflichtigen) brauchen Honorarnoten mit einer HN-Nummer.
Diese muss irgendwie eingegeben werden können.

**Comment by irisSchaffer** [comment]
In https://github.com/irisSchaffer/OEBS_Honorarnoten/commit/e39d1faad085a9f213c0d6e1961ed766d49d2d53 gelöst
